name: Windows publish

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-windows:
    name: Build windows exe
    runs-on: windows-2025
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install uv
        run : |
          python -m pip install uv

      - name: Install CLI dependencies
        run : |
          uv venv --clear
          uv pip install pyinstaller
          uv pip install .

      - name: Build CLI
        run: uv run pyinstaller build_files/windows/hydrusvideodeduplicator.spec

      # Install the GUI dependencies after the CLI build to avoid bundling unnecessary
      # GUI dependencies in the CLI build. Pyinstaller bundles all dependencies by default.
      - name: Install GUI dependencies
        run : |
          uv venv --clear
          uv pip install pyinstaller
          uv pip install ".[gui]"

      - name: Build GUI
        run: uv run pyinstaller build_files/windows/hydrusvideodeduplicator-gui.spec

      - name: Upload
        uses: softprops/action-gh-release@37fd9d0351a2df198244c8ef9f56d02d1f921e20
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/hydrusvideodeduplicator.exe
            dist/hydrusvideodeduplicator-gui.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
